# Generated by Django 5.0.3 on 2024-03-17 17:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('QRcode', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('openQuestionMode', models.BooleanField(default=True)),
                ('correctAnswer', models.TextField(blank=True, null=True)),
                ('correctAnswerInPosibleAnswers', models.CharField(blank=True, max_length=1, null=True)),
                ('pointsForQuestion', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaBaza.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openAnswer', models.TextField(blank=True, null=True)),
                ('closeAnswer', models.CharField(blank=True, max_length=1, null=True)),
                ('status', models.CharField(choices=[('new', 'Waiting for check'), ('checked_positive', 'Answer correct'), ('checked_negative', 'Answer wrong')], default='new', max_length=60)),
                ('pointsForAnswer', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaBaza.groups')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaBaza.questions')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaBaza.groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaBaza.users')),
            ],
        ),
    ]
