# Generated by Django 5.0.6 on 2024-05-08 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaBaza', '0002_alter_groupmembers_user_delete_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembers',
            name='user',
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
