# Generated by Django 5.0.6 on 2024-05-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaBaza', '0004_usersanswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='correctAnswer',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='correctAnswerInPosibleAnswers',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='openQuestionMode',
        ),
        migrations.AddField(
            model_name='questions',
            name='correct_answer',
            field=models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_1',
            field=models.CharField(default='Option 1', max_length=255),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_2',
            field=models.CharField(default='Option 2', max_length=255),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_3',
            field=models.CharField(default='Option 3', max_length=255),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_4',
            field=models.CharField(default='Option 4', max_length=255),
        ),
    ]
