# Generated by Django 5.0.6 on 2024-05-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaBaza', '0005_remove_questions_correctanswer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='pointsForQuestion',
            new_name='points_for_question',
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_4',
            field=models.CharField(default='', max_length=255),
        ),
    ]
